[package]
name = "rio"
version = "0.0.1"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/raphamorim/rio"
documentation = "https://github.com/raphamorim/rio#readme"
description = "Rio termina app"

[dependencies]
wgpu = { workspace = true }
tokio = { version = "1.26.0", features = ["full"] }
winit = "0.28.3"
libc = "0.2.140"
image = { version = "0.24.5", default-features = false, features = ["ico"] }
bytemuck = { workspace = true }
mio = "0.6.20"
base64 = "0.21.0"
mio-extras = "2"
parking_lot = "0.12"
vte = { version = "0.11.0", default-features = false }
copypasta = { version = "0.8.1", default-features = false }
teletypewriter = { workspace = true }
colors = { path = "../colors" }
config = { path = "../config" }
dirs = "5.0"
unicode-width = "0.1.5"
bitflags = "2.0.2"
serde = { workspace = true }
glyph_brush = "0.7.7"
lazycell = "1"

[package.metadata.bundle]
name = "Rio"
identifier = "com.raphaelamorim.rio"
#icon = ["src/32x32.png", "128x128.png", "128x128@2x.png"]
icon = ["src/screen/window/resources/images/logo-macos.ico"]
version = "1.0.0"
resources = ["src/screen/window/resources"]
copyright = "Copyright (c) Raphael Amorim 2023. All rights reserved."
category = "Developer Tool"
short_description = "A terminal application"
long_description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat.
"""
# deb_depends = ["libgl1-mesa-glx", "libsdl2-2.0-0 (>= 2.0.5)"]