[workspace]
members = [
  "ansi",
  "tty",
  "config",
  "rio"
]
resolver = "2"

[profile.release]
opt-level = "z"

[profile.dev]
# https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/
split-debuginfo = "unpacked"