[workspace]
members = [
  "tty",
  "colors",
  "config",
  "crosswords",
  "rio"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.155", features = ["derive"] }

[profile.release]
opt-level = "z"

[profile.dev]
# https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/
split-debuginfo = "unpacked"