[package]
authors = ["Raphael Amorim <rapha850@gmail.com>"]
description = "Rio proc macros"
repository = "https://github.com/alacritty/vte"
name = "rio_proc_macros"
license = "MIT"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
quote = "1.0.2"
