[alias]
test-colors = "test --release -p colors --"
test-config = "test --release -p config --"
test-rio = "test --release -p rio --"

[target.wasm32-unknown-unknown]
rustflags = [
    # Enabled unstable APIs from web_sys
    "--cfg=web_sys_unstable_apis"
]
runner = 'wasm-bindgen-test-runner'