[package]
name = "config"
version = "0.0.1"
edition = "2021"

[dependencies]
toml = "0.5"
dirs = "4.0"
colors = { path = "../colors" }
regex = "1.7.1"
serde = { version = "1.0", features = ["derive"] }

