[package]
name = "renderer"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
wgpu = { workspace = true }
bytemuck = { workspace = true }
winit = { workspace = true }
glyph_brush = "0.7.7"

[dev-dependencies]
tokio = { workspace = true }