[package]
name = "tty"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
authors = { workspace = true }

[dependencies]
libc = "0.2.140"