[package]
name = "ansi-machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vte = "0.11.0"
tty = { path = "../tty" }
crosswords = { path = "../crosswords" }