name: Release Canary

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: macos-11.0
    name: Release Canary
    permissions:
      contents: write
      discussions: write

    env:
      CARGO_TERM_COLOR: always
      GITHUB_REPOSITORY: raphamorim/rio
      RUST_BACKTRACE: full
      TAG: canary
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get all changed *.rs file(s) or any file in the misc folder excluding the docs folder
        id: changed-files-excluded
        uses: tj-actions/changed-files@v36
        with:
          files: |
            **/*.rs
            misc
          files_ignore: docs

      - name: Run step if any *.rs file(s) or any file in the misc folder change
        if: steps.changed-files-excluded.outputs.any_changed == 'true'
        run: |
          echo "One or more *.rs file(s) or any file in the static folder but not in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-excluded.outputs.all_changed_files }}"

      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - run: rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - run: make release-macos
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: 'canary-${{ github.sha }}'
          tag_prefix: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release canary
        uses: softprops/action-gh-release@v1
        with:
          name: canary
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            release/macos-rio.zip
            LICENSE
