on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTC_BOOTSTRAP: 1

jobs:
  lint:
    strategy:
      matrix:
        target:
          include:
            - os: macOS-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    name: Lint
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # make sure all code has been formatted with rustfmt and linted with clippy
      - run: rustup component add rustfmt clippy
      - name: rustfmt
        run: cargo fmt -- --check --color always

      # - name: cargo clippy
      #   run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    strategy:
      matrix:
        target:
          include:
            - os: macOS-latest
            target: x86_64-apple-darwin
          # - x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    env:
      RUSTUP_UNPACK_RAM: "26214400"
      RUSTUP_IO_THREADS: "1"
    name: Test
    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: '--release'