name: Release Nightly

on:
  push:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always
  GITHUB_REPOSITORY: raphamorim/rio
  RUST_BACKTRACE: full

jobs:
  release:
    runs-on: macos-11.0
    name: Release Nightly
    permissions:
      contents: write
      discussions: write

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - run: rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - run: make release-macos
      - name: Release nightly
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          name: nightly
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/macos-rio.zip
            LICENSE
