name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  GITHUB_REPOSITORY: raphamorim/rio
  RUST_BACKTRACE: full

jobs:
  release:
    runs-on: macos-11.0
    name: Release
    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"
          cache-targets: "true"

      - run: rustup toolchain install stable --profile minimal
      - run: rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - run: mkdir release
      - run: cargo install cargo-bundle
      - run: make app-universal
      - run: make pack-app-universal

      - name: Release nightly
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          name: nightly
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/macos-rio.zip
            LICENSE

      - name: Release version
        uses: softprops/action-gh-release@v1
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/macos-rio.zip
            LICENSE
