name: Release

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release-macos-x86:
    name: Release x86_64-apple-darwin
    runs-on: macOS-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
    env:
      RUSTFLAGS: "-C target-cpu=native"
      RUST_BACKTRACE: full

    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }}
      - run: mkdir release
      - run: cargo install cargo-bundle
      - run: make pack-osx-x86
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/macos-x86.zip
            LICENSE
